src/exercise/02.md

When the React is rendered it will not have "className" it should be "class"

Fixes output that should be generated

---

src/exercise/01.html

In the instructions for inserting the text it specifies the use of
`div.textConent` when it should be `div.textContent`

Fixes typo in first exercise instructions

---

.npmrc

Summary of #78: @coreysmithdesign was having trouble in this repo getting packages from npm, and it turns out his network was pretty much blocking non-secure network requests. They fixed it themselves and closed the issue, but I figured a commit to amend the npm registry specified in `.npmrc` to use `https` instead of `http` is a good idea.
Can't imagine we're intentionally requesting `http://registry.npmjs.org/` instead of `https://registry.npmjs.org/`, but hopefully someone who knows more than I on this will confirm or reject 😄 
Seems like the same thing happens in other workshop repos as well... https://github.com/kentcdodds/react-hooks/blob/main/.npmrc

fix #78: use https for the npm registry

---

package-lock.json
package.json

More about the problem: https://stackoverflow.com/questions/46871567/webstorm-auto-completion-does-not-work-for-react-js/46871647

Add @types/react and @types/react-dom to support autocomplete functionality in Webstorm

---

src/exercise/04.md

The instructions define a `message` signature different than the one provided by 💰 Marty the Money Bag in the exercise file itself. In addition, following the instructions signature will force a refactor when updating to use `React.createElement` in Extra Credit 1.
If this is intentional (perhaps to keep the instructions as simple as possible), then please close this PR. Opening in case I'm not the only one a bit mislead by the unnecessary difference.

Update Exercise 04 instructions

---

README.md

Node 17 is not supported (e7eca6e13d68685c9a967733155af539c6dc9315) but was still listed in the README.
Edit: I've discovered this is an issue with the other repos for this course also, but haven't made PR's to the other repos - would be good to fix everywhere though.

Node 17 isn't supported so remove from README

---

src/__tests__/06.extra-2.js

Upper and lower case are both accounted for, but `lower case` and `lowercase` are both acceptable spellings. Adding an optional whitespace for learners who choose to spell it without a space.

Adjust regex in test

---

src/final/05.extra-2.js

**2. 💯 accept a size prop to encapsulate styling.  ------- 5th Assignment extra credit 2**
For this challenge we are sending **size** as props to **Box component** so **className** is no longer necessary and it's not being used.

Fix: Removing className as props from Box component - 05-Extra 2

---

src/exercise/07.js
src/final/07.extra-1.js
src/final/07.js
src/styles.css

This PR aims to make the exercise 7 "extra" demo more accessible by implementing the work proposed & discussed in #321.
- No way to pause continuous motion
- No input labels
https://user-images.githubusercontent.com/93289772/213559809-14982832-5cf4-4b62-876b-bdd967e1daad.mov
- Checkbox allows course-takers to pause auto-shuffle (is checked, by default)
- Inputs are all labelled
https://user-images.githubusercontent.com/93289772/213559837-afdb2ab0-d8bd-4efb-afd5-5a1458a8c1c4.mov

feat: add auto-shuffle checkbox and input labels to keys demo (exercise 7 extra 1)

---

src/exercise/07.md

- This change removes the duplicate list element present in the `Rendering Arrays` tutorial.
-  duplicate list in docs preview

Remove an extra list element from `Rendering Arrays` tutorial

---

src/exercise/06.md

The previous link still linked to the outdated React docs, had to click another link on there to get to the up-to-date documentation.

Update 06.md with up-to-date link to React documentation

---

exercises/06.styling/03.problem.size-prop/README.mdx
exercises/06.styling/03.problem.size-prop/index.tsx
exercises/07.forms/01.problem.form/index.tsx

1. Union -> intersection. Resolves #372
2. Explicit instruction for adding a submit button

small exercise updates

---

exercises/02.raw-react/01.problem.elements/README.mdx

Edit typo in line 33 from "you're" to "your".

Edit typo in README.mdx

---

exercises/07.forms/04.problem.submit/README.mdx

Small typo prventing vs. preventing.

Fix typo in Forms Submission text

---

exercises/02.raw-react/02.problem.nesting/README.mdx
exercises/03.using-jsx/02.problem.interpolation/README.mdx
exercises/04.components/01.solution.function/README.mdx
exercises/04.components/02.solution.raw/README.mdx
exercises/04.components/03.problem.jsx/README.mdx
exercises/04.components/04.problem.props/README.mdx
exercises/04.components/04.problem.props/index.html

As I'm working my way through the workshop material, I'm tackling little typo things here and there. 🤓 
I was going to wait until the very end to open a PR with all of them, but I think for me personally I'd rather have a couple of smaller PR's than one big one. 
* dc27dbe6895d6c5dee0a08b2561088aa313d7622: We've got a hint and a tip side-by-side using inconsistent formatting. Totally not a problem, but if I've got a branch named "nitpicks" that's a great place to put a commit normalizing them!
* 90cf03874322c414107e97c28faf4ad1cea43397: "React" as a proper noun deserves an uppercase R to trumpet its entrance
* b811a22a35dc9b773ea3c57a78a01ff152929fbe: Samesies as above
* ce045525b0666b66a947e0712dcae98b807c6546: It _might_ be OK to use "all that nicer" but I bet this is just a typo
* …

Copywriting nitpicks (Modules 01.01-04.01)

---

exercises/09.errors/02.problem.show-boundary/README.mdx

Having that code block in a blockquote makes its text italicized, bold and not aligned with the left edge of the content. If this was by design, please disregard this PR!

Remove blockquote around code block

---

exercises/07.forms/04.solution.submit/action.test.ts

As the spec is written, performing the extra credit will fail the tests. That's because the spec expects certain form attributes, while the extra credit says we can remove those attributes altogether.
One thing both of those conditions have in common (which the student must change if they want the test to pass) is the form must no longer GET from the endpoint.
While an argument for "progressive enhancement" _could_ be made here, I agree with Kent's comment in the accompanying video that this is a fully client-side app where passing the submission to the server doesn't really make sense.
Alternatively, the "extra credit" comment could be updated to say something like "FYI, the tests won't pass if you do this extra credit!"

Align test spec for 07.04 with extra credit

---

exercises/03.using-jsx/01.solution.compiler/README.mdx
exercises/03.using-jsx/05.problem.fragments/README.mdx

Update `README.mdx` files in `exercises/03.using-jsx` for the compiler
solution and fragments problem, likely improving explanations or
instructions for these JSX-related topics.

docs(jsx): update README files for compiler and fragments

---

exercises/05.typescript/06.problem.satisfies/README.mdx
exercises/05.typescript/README.mdx
exercises/06.styling/01.problem.style/index.tsx
exercises/06.styling/README.mdx
exercises/08.inputs/01.problem.checkbox/index.tsx
exercises/08.inputs/03.problem.radio/README.mdx

Just like #386 here comes another PR to make the instructions a little clearer. Most of these edits are just little fiddly typo fixes, but I did a little bit of rephrasing and clarifying on the last 3 listed here.
* 1d595f1bc3eaf7e7dfc0325840d885d6ac1b2922: "Note: we're..." -> "Note: We're..."
* 7b1d195857a648ddd7accd5b95e2c62833e2684c: "Your's truly" -> "Yours truly"
* 0a07c9d5ab3f3dd735e6460e55468fded0c1317d: "react" -> "React"
* 9886d6b07ebb542779f04438f2a82db36afcec88: "sizelss" -> "sizeless"
* 4abd92874ddd00d5ce9e035b993b5da62ebedec6: Letting the student know the input name the integration test needs
* 9d0268e412726f434891fdb2a9c671c51916b3ce: This started as a typo fix, but then I reworded for clarity
* 5b5e53a9ffb5432731145fff1d4f8cad2b6df838: The checkbox lesson references …

Fix copywriting nitpicks (Modules 5-8)

---

exercises/06.styling/02.solution.component/README.mdx

One of the tests need to have that Box component exported to succeed, and the video doesn't mention it.

Instruct students to export the box component

---

exercises/10.arrays/01.solution.key-prop/README.mdx
exercises/10.arrays/README.mdx

Wahoo! That's all the nitpicks from me for this workshop, one last PR to cap it off.
- 85fbfdb4400e54cdd8b97d3e7e5e31de44081b3f: Typo: "this warning" -> "a warning"
- 6f8add98a5a348a22a8097cda51475ce93cb8959: Typo: "an" -> "and"
- 7ed5890299c7dd5885b9e7ae42004740e9095aef: "Note," is a little confusing when we have "Note:" sometimes

Nitpicks for Ch. 10

---

exercises/07.forms/04.problem.submit/index.tsx
exercises/08.inputs/05.problem.default-value/README.mdx

`exercises/07.forms/04.problem.submit/index.tsx`
* Removed an additional/redundant `'the'` word.
`exercises/08.inputs/05.problem.default-value/README.mdx`
* Replaced `'the'` -> `'to'` as that seemed to be the intention with the sentence.

docs: fix a couple of typos in 07.forms & 08.inputs

---

exercises/09.errors/01.solution.composition/error-boundary.test.ts
exercises/09.errors/02.solution.show-boundary/error-boundary.test.ts
exercises/09.errors/03.solution.reset/error-boundary.test.ts

The wording of the errors varies greatly between e.g. Chrome and Firefox. Since tests were (presumably) written by someone using Chrome, users using Firefox wouldn't be able to get the tests to work. In this PR, tests are modified in such a way that they still fail on the initial playground version, and succeed when copying over the solution, for both browsers.
For completeness sake, here is how Firefox and Chrome word the error:
9.1 Chrome: `invalid time value`, Firefox: `invalid date`
9.2 Chrome: `Cannot read properties of null (reading 'toUpperCase')`, Firefox: `accountType is null`
9.3 same as 9.2
P.S. this is my very first contribution to an open source project ever :rocket:

Stop testing wording of errors

---

exercises/09.errors/01.problem.composition/index.tsx

The automated tests are looking for something like `<div role="alert">{ error_message }</div>`, so this just makes that explicit in the user instructions.

update description in error boundaries lesson 01 to match automated tests
