- src/exercise/06.md
Small typo but thought I'd pr 😄
> Typo in exercise 06 description

- README.md
Added sentence also includes three common issues myself and others have discussed in discord a lot ha...
> update README to include fix from issue #27

- src/final/04.extra-4.html
According to the exercise 4, we want to check that both `greeting` and `subject` are passed to avoid a "hanging" comma. But in this file it is actually missed.
> Add a comma to final 04.extra-4.html

- src/exercise/07.md
> Fix a typo on exercise 7

- src/final/01.extra-1.html
In the base exercise, we have an id of "root" on the div, and in the extra credit we are supposed to programmatically reproduce this element, so I thought it made sense to also replicate the root id.
> Add 'root' id to root element to replicate the base exercise.

- src/exercise/07.md
> Small typo in 07.md file

- src/exercise/03.md
> Fix small typo in 03.md

- src/exercise/06.md
The earlier sentence was a little confusing to read (for me at least) while I was going through the course.
> Fix: Language in 06.md

- src/exercise/06.md
It was unclear in the markdown file on how to display the error.
I think bullet point 4 is necessary as it is unlikely a developer going through this workshop might have in-depth  understanding of ARIA. It still forces the developer to dig into the test and find out the value on their own.
> [docs] Clarification regarding error display

- src/exercise/06.md
Reason: current wording might be misconstrued.
> [docs] Clarification

- src/exercise/04.md
seems like the example of propTypes should be changed a bit to better match your solution.
for people unfamiliar with propTypes this example will be a better hint to finish the solution by themselves without looking into the final answer.
> changed the example of manual propType

- src/exercise/06.md
Tiny typo fixes and clarifications.
Regarding "anytime", I went with this: [Anytime vs any time](https://writingexplained.org/anytime-vs-any-time-difference)
> docs: Clarification and typo fixes

- src/exercise/06.js
at first I thought "why don't we have name attribute? let me add it anyways". now that I watched the solution videos, it should be there for sure ;)
> added name attribute to input element

- src/exercise/06.md
- Added instruction to disable button
- Added instruction to add `role="alert"`
- Didn't add an explanation so the text doesn't get too long, but add a link explaining it.
This PR just add more instructions so it can pass line [22 and 23](https://github.com/kentcdodds/react-fundamentals/blob/main/src/__tests__/06.extra-2.js#L22-L23) from `06.extra-02.js` test.
> feat(06): add more instructions to extra-credit

- src/exercise/01.md
On 01.md, moves <script> inside body
> Note: now it's also more in line with the solution provided
> docs: 01.md move script in body

- src/__tests__/06.js
in order to have the test pass after extra-2 is being implemented
in extra-2 validation is added and the form can not be submitted when the username contains upper case letters.
> test: use lowercase username to test form

- Dockerfile
- README.md
- docker-compose.yml
Hi Kent,
For anyone who has issues with the local setup I have created docker support. I hope you accept this pull request and save time for anyone who knows docker.
Thanks for being awesome and take care :)
> Adds Docker setup

- src/exercise/01.html
to give more context for `<script type="module">`
> docs(01.html): suggest documentation script module

- src/exercise/07.js
Reduces the number of operations performed by the `addItem` function in the  `Rendering Arrays` exercise.  While this "improvement" is quite trivial, I also feel that the update slightly improves readability.
> Improve performance of Rendering Arrays exercise

- src/final/07.js
Continuation of [PR# 171](https://github.com/kentcdodds/react-fundamentals/pull/171). I realized after PR# 171 was merged that I should have also updated the `Rendering Arrays` example in the `src/final` directory.
> Improve performance of Rendering Arrays final

- src/exercise/02.html
When going through this exercise, I accidently removed lines 7-10 because I thought "delete this line" text on lines 7 and 10 meant to delete all the lines between 7 and 10 (including 7-10).
It wasn't until I took a peek at the solution that I realized I was only supposed to remove the comment lines on lines 7 and 10.
Not sure if others experienced this. But I felt it would be a good UX writing proposal to make :)
> Edit the delete text around the unpkg script tags

- src/exercise/07.md
See  https://github.com/kentcdodds/react-fundamentals/commit/2c8eb3a92d5994d8a238b3fda5f81ec7dbe7ddd9#r55928301
> Docs: Improving extra credit on 7th lesson

- README.md
> add syntax command

- src/exercise/05.js
Hi! I improved the instructions for exercise 5.
> improve instructions for exercise 5

- src/exercise/04.md
- src/exercise/05.md
Hi! I removed the word "below" from the Background section in `05.md` because there were no divs below the sentence. I also run `npm run format`.
> improve background in 05.md

- src/exercise/06.md
Hi. I improved the instructions for extra credits in `06.md`. I replaced `exercise` with `extra credit` because they are not in the Exercise section but the Extra Credit section.
> Improve the instructions for extra credits in 06.md

- src/exercise/03.html
I was a bit confused by whether the "💣 remove this line" comment meant I was supposed to delete just the comment delimiters, or the content in between.
Instead, I followed [the pattern in exercise 02 when adding the React scripts](https://github.com/kentcdodds/react-fundamentals/blob/main/src/exercise/02.html#L7-L11), which I found more clear.
> Edit "remove this line" comment

- src/exercise/05.js
I found the instructions for the styling exercise (05) confusing. 
I attempted to clean it up and make it more clear. I'm open to iterating!
> Make instructions more clear in exercise 05

- src/exercise/04.md
- src/exercise/06.md
Some Dominic the Document 📜 links were plain text, and so I'd have to highlight-copy-paste to view them.
I just made them hyperlinks. Now we can click on them directly from the document!
> Make Dominic the Document links clickable

- README.md
Made the feedback links clickable
> make feedback link clickable - README.md

- package.json
- adding support to node engine 19, here's the [reference](https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9)
> fix: engine supported version

- exercises/01.js-hello-world/01.problem.hello/index.html
this PR bring some enhancement to  `01.js-hell-world` -> `problem.hello`:-
- 🐨 Added extra step instruction to "Get the root div using the JavaScript DOM API".
- 🎯 This step was included to ensure the correct target element is obtained before proceeding with the manipulations.
- 🎯 Getting the root div using the DOM API is an essential step towards achieving the desired outcome.
- 📜 Setting `getElementById`: [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById)
- 🐨 Removed the instruction to `Append the text 'Hello World' to the div`.
- 🎯 This decision was made to simplify the code and make it more straightforward.
- 🎯 Moving from appending text to setting the `textContent` property aligns better with the final solution and makes it easier to reach …
> FEAT: Add more MDN links and steps for 01.js-hell-world -> problem.hello

- package-lock.json
- package.json
Fix issue #364 and update `@types/react` and  `@types/react-dom` to latest
> FEAT: Updated dependencies: React and React DOM to v18.2.0

- exercises/08.errors/01.problem.composition/README.mdx
- exercises/08.errors/01.problem.composition/index.tsx
- exercises/08.errors/02.problem.show-boundary/README.mdx
- exercises/08.errors/02.problem.show-boundary/index.tsx
- exercises/08.errors/03.problem.reset/README.mdx
- exercises/08.errors/03.problem.reset/index.tsx
Hey @kentcdodds ! 👋 I've made some improvements to our error handling and user experience in this PR. Here's a breakdown of the changes:
**Changes in `exercises/08.errors/01.problem.composition/README.mdx`:**
- Renamed the existing `App` component to `OnboardingForm` for clarity.
- Add references to the documentation of the package 😉
**Changes in `exercises/08.errors/01.problem.composition/index.tsx`:**
- Added `type` flag for importing `FallbackProps` from `react-error-boundary`.
- Added a placeholder for creating the `ErrorFallback` component.
**Changes in `exercises/08.errors/02.problem.show-boundary/README.mdx`:**
- Thought it will be fun if we show student the error message that he/she see to make sure that he is right 
**Changes in …
> FEAT: enhance user experience 🛠️✨ and fix typos at errors module

- exercises/07.forms/05.problem.action/index.tsx
Remove a confusing line 
clarify with capitalization that FormData is the type of object
> Clarify Form Action problem comments

- exercises/09.errors/README.mdx
Simply removing a couple of words that accidentally made their way in.
> Removing extra words
